export { ReactComponent as HomeIcon } from './home.svg'
export { ReactComponent as ScrapIcon } from './scrap.svg'
export { ReactComponent as MagnifierIcon } from './magnifier.svg'
export { ReactComponent as CalenderIcon } from './calender.svg'
export { ReactComponent as NoScrapIcon } from './noscrap.svg'
export { ReactComponent as SubtracteIcon } from './star-fill.svg'
